server:
  port: 8080 # 设置端口号
  servlet:
    context-path: /  # 设置服务器的访问路径
spring:
  main:
    allow-circular-references: true
  config:
    import: config/knife4jConfig.yml, config/DBConfig.yml # 导入相关的配置信息

# 设置日志
logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

