# 配置数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://59.110.139.253:3306/doordash
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abcABC123!
    type: com.alibaba.druid.pool.DruidDataSource
# 配置mybatis信息
mybatis:
  config-location: classpath:config/mybatis-config.xml
